"""add access grants and credential hierarchy"""
from alembic import op
import sqlalchemy as sa
from typing import Sequence, Union

revision: str = 'e7ea9183b0a5'
down_revision: Union[str, None] = '397abf27e6f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_grants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grace_days', sa.Integer(), nullable=False),
    sa.Column('frozen_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'application_id', name='uq_access_grant_org_app')
    )
    op.create_index(op.f('ix_access_grants_application_id'), 'access_grants', ['application_id'], unique=False)
    op.create_index(op.f('ix_access_grants_organization_id'), 'access_grants', ['organization_id'], unique=False)
    op.create_index(op.f('ix_access_grants_plan_id'), 'access_grants', ['plan_id'], unique=False)
    op.create_table('notification_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('access_grant_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('days_before', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('recipients', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['access_grant_id'], ['access_grants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_grant_id', 'event_type', 'days_before', name='uq_notification_rule_event')
    )
    op.create_index(op.f('ix_notification_rules_access_grant_id'), 'notification_rules', ['access_grant_id'], unique=False)
    op.create_table('notification_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('notification_key', sa.String(length=300), nullable=False),
    sa.Column('access_grant_id', sa.String(length=36), nullable=True),
    sa.Column('credential_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['access_grant_id'], ['access_grants.id'], ),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_key', name='uq_notification_log_key')
    )
    op.create_index(op.f('ix_notification_log_access_grant_id'), 'notification_log', ['access_grant_id'], unique=False)
    op.create_index(op.f('ix_notification_log_credential_id'), 'notification_log', ['credential_id'], unique=False)
    op.add_column('applications', sa.Column('owner_emails', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('credentials', sa.Column('access_grant_id', sa.String(length=36), nullable=True))
    op.add_column('credentials', sa.Column('parent_id', sa.String(length=36), nullable=True))
    op.add_column('credentials', sa.Column('root_id', sa.String(length=36), nullable=True))
    op.add_column('credentials', sa.Column('kind', sa.String(length=20), nullable=False, server_default='ROOT'))
    op.add_column('credentials', sa.Column('path', sa.String(length=1000), nullable=True))
    op.add_column('credentials', sa.Column('depth', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('credentials', sa.Column('secret_hash', sa.Text(), nullable=True))
    op.add_column('credentials', sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('credentials', sa.Column('frozen_reason', sa.Text(), nullable=True))
    op.add_column('credentials', sa.Column('permissions', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('credentials', sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True))
    with op.batch_alter_table('credentials') as batch_op:
        batch_op.alter_column('secret_ciphertext', existing_type=sa.Text(), nullable=True)
    op.create_index(op.f('ix_credentials_access_grant_id'), 'credentials', ['access_grant_id'], unique=False)
    op.create_index(op.f('ix_credentials_parent_id'), 'credentials', ['parent_id'], unique=False)
    op.create_index(op.f('ix_credentials_root_id'), 'credentials', ['root_id'], unique=False)
    with op.batch_alter_table('credentials') as batch_op:
        batch_op.create_foreign_key('fk_credentials_access_grant', 'access_grants', ['access_grant_id'], ['id'])
        batch_op.create_foreign_key('fk_credentials_root', 'credentials', ['root_id'], ['id'])
        batch_op.create_foreign_key('fk_credentials_parent', 'credentials', ['parent_id'], ['id'])
    op.add_column('plans', sa.Column('max_children', sa.Integer(), nullable=False, server_default='10'))
    op.add_column('plans', sa.Column('max_depth', sa.Integer(), nullable=False, server_default='4'))
    op.add_column('plans', sa.Column('default_term_days', sa.Integer(), nullable=False, server_default='365'))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'default_term_days')
    op.drop_column('plans', 'max_depth')
    op.drop_column('plans', 'max_children')
    with op.batch_alter_table('credentials') as batch_op:
        batch_op.drop_constraint('fk_credentials_parent', type_='foreignkey')
        batch_op.drop_constraint('fk_credentials_root', type_='foreignkey')
        batch_op.drop_constraint('fk_credentials_access_grant', type_='foreignkey')
        batch_op.alter_column('secret_ciphertext', existing_type=sa.Text(), nullable=False)
    op.drop_index(op.f('ix_credentials_root_id'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_parent_id'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_access_grant_id'), table_name='credentials')
    op.drop_column('credentials', 'last_used_at')
    op.drop_column('credentials', 'permissions')
    op.drop_column('credentials', 'frozen_reason')
    op.drop_column('credentials', 'frozen_at')
    op.drop_column('credentials', 'secret_hash')
    op.drop_column('credentials', 'depth')
    op.drop_column('credentials', 'path')
    op.drop_column('credentials', 'kind')
    op.drop_column('credentials', 'root_id')
    op.drop_column('credentials', 'parent_id')
    op.drop_column('credentials', 'access_grant_id')
    op.drop_column('applications', 'owner_emails')
    op.drop_index(op.f('ix_notification_log_credential_id'), table_name='notification_log')
    op.drop_index(op.f('ix_notification_log_access_grant_id'), table_name='notification_log')
    op.drop_table('notification_log')
    op.drop_index(op.f('ix_notification_rules_access_grant_id'), table_name='notification_rules')
    op.drop_table('notification_rules')
    op.drop_index(op.f('ix_access_grants_plan_id'), table_name='access_grants')
    op.drop_index(op.f('ix_access_grants_organization_id'), table_name='access_grants')
    op.drop_index(op.f('ix_access_grants_application_id'), table_name='access_grants')
    op.drop_table('access_grants')
    # ### end Alembic commands ###
